import { ProjectState, ProjectScores } from '@/types/project';
import { PROJECT_TYPES } from '@/data/projectTypes';
import { FEATURES } from '@/data/features';
import { INTEGRATIONS } from '@/data/integrations';
import { formatPrice } from './pricingEngine';
import { formatWeeks } from './timelineEngine';

function getProjectTypeLabel(state: ProjectState): string {
  const pt = PROJECT_TYPES.find(p => p.id === state.projectType);
  return pt ? pt.label : 'Not specified';
}

function getFeatureLabels(state: ProjectState): string[] {
  return state.features.map(fid => {
    const f = FEATURES.find(feat => feat.id === fid);
    return f ? f.label : fid;
  });
}

function getIntegrationLabels(state: ProjectState): string[] {
  return state.integrations.map(iid => {
    const i = INTEGRATIONS.find(integ => integ.id === iid);
    return i ? i.label : iid;
  });
}

function generateExclusions(state: ProjectState): string[] {
  const exclusions: string[] = [];
  if (state.contentReadiness !== 'ready') exclusions.push('Content entry and population not included');
  if (!state.features.includes('api-integrations')) exclusions.push('Custom API development beyond listed integrations excluded');
  if (!state.maintenanceNeeded) exclusions.push('Ongoing maintenance and support not included');
  if (state.imageAssets !== 'full-art') exclusions.push('Custom photography and video production excluded');
  if (!state.features.includes('multi-language')) exclusions.push('Translation and localization excluded');
  if (!state.documentationRequired) exclusions.push('Technical documentation excluded');
  exclusions.push('Third-party software licenses and hosting costs');
  exclusions.push('Scope changes after design approval');
  return exclusions;
}

function generateAssumptions(state: ProjectState): string[] {
  const assumptions: string[] = [];
  assumptions.push('Client provides timely feedback within agreed revision windows');
  if (state.contentReadiness !== 'ready') assumptions.push('Content delivery will not delay development phase');
  if (state.hostingResponsibility === 'client') assumptions.push('Client manages their own hosting environment');
  if (state.hostingResponsibility === 'agency') assumptions.push('Hosting setup is included in scope and invoiced separately');
  assumptions.push('All required third-party API keys and accounts are provided by client');
  if (state.branding === 'existing') assumptions.push('Existing brand assets are provided in vector/print-ready format');
  if (state.migration !== 'none') assumptions.push('Source platform access provided at project kickoff');
  assumptions.push('Project proceeds with a single primary point of contact on client side');
  return assumptions;
}

export function generateMarkdown(state: ProjectState, scores: ProjectScores): string {
  const lines: string[] = [];
  const ptLabel = getProjectTypeLabel(state);
  const featureLabels = getFeatureLabels(state);
  const integrationLabels = getIntegrationLabels(state);
  const exclusions = generateExclusions(state);
  const assumptions = generateAssumptions(state);

  lines.push(`# ${state.name} — Project Scope`);
  lines.push('');
  lines.push(`*Generated by BriefForge on ${new Date().toLocaleDateString()}*`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Project Overview');
  lines.push('');
  lines.push(`**Type:** ${ptLabel}`);
  lines.push(`**Complexity:** ${scores.complexityLabel} (${scores.complexity} points)`);
  lines.push(`**Risk Level:** ${scores.riskLabel}`);
  lines.push(`**Scope Health:** ${scores.scopeHealth}%`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Included Deliverables');
  lines.push('');
  featureLabels.forEach(f => lines.push(`- ${f}`));
  if (integrationLabels.length > 0) {
    lines.push('');
    lines.push('**Integrations:**');
    integrationLabels.forEach(i => lines.push(`- ${i}`));
  }
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Exclusions');
  lines.push('');
  exclusions.forEach(e => lines.push(`- ${e}`));
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Assumptions');
  lines.push('');
  assumptions.forEach(a => lines.push(`- ${a}`));
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Risks');
  lines.push('');
  if (scores.riskFlags.length === 0) {
    lines.push('- No major risks identified');
  } else {
    scores.riskFlags.forEach(flag => {
      lines.push(`- **${flag.clientLabel}** — ${flag.description}`);
      lines.push(`  *Mitigation: ${flag.mitigation}*`);
    });
  }
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Timeline Estimate');
  lines.push('');
  lines.push(`| Phase | Duration |`);
  lines.push(`|-------|----------|`);
  lines.push(`| Discovery | ${formatWeeks(scores.timeline.discovery)} |`);
  lines.push(`| Design | ${formatWeeks(scores.timeline.design)} |`);
  lines.push(`| Development | ${formatWeeks(scores.timeline.development)} |`);
  lines.push(`| QA & Testing | ${formatWeeks(scores.timeline.qa)} |`);
  lines.push(`| Launch | ${formatWeeks(scores.timeline.launch)} |`);
  lines.push(`| **Total** | **${formatWeeks(scores.timeline.total)}** |`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Budget Estimate');
  lines.push('');
  lines.push(`| Tier | Estimate |`);
  lines.push(`|------|----------|`);
  lines.push(`| Minimum | ${formatPrice(scores.pricing.minimum)} |`);
  lines.push(`| Realistic | ${formatPrice(scores.pricing.realistic)} |`);
  lines.push(`| Premium | ${formatPrice(scores.pricing.premium)} |`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('*Estimates are indicative and subject to detailed discovery.*');

  return lines.join('\n');
}

export function generateProposalSummary(state: ProjectState, scores: ProjectScores): string {
  const ptLabel = getProjectTypeLabel(state);
  const featureLabels = getFeatureLabels(state).slice(0, 8);
  const projectTitle = state.name ? `${state.name} — ` : '';

  return `${projectTitle}${ptLabel} Project Scope Summary
Generated by BriefForge on ${new Date().toLocaleDateString()}

Thank you for the opportunity to scope your ${ptLabel} project.

Based on our review, this is a ${scores.complexityLabel.toLowerCase()} engagement involving ${state.features.length} core features across an estimated ${formatWeeks(scores.timeline.total)}. Our realistic budget estimate comes in at ${formatPrice(scores.pricing.realistic)}, with a range of ${formatPrice(scores.pricing.minimum)} – ${formatPrice(scores.pricing.premium)} depending on final scope.

Key deliverables include: ${featureLabels.join(', ')}.

${scores.riskFlags.length > 0 ? `We've noted ${scores.riskFlags.length} risk item(s) that should be addressed in discovery: ${scores.riskFlags.map(f => f.clientLabel).join(', ')}.` : 'Initial risk assessment is favorable.'}

We look forward to discussing this in more detail. This scope summary is preliminary and will be refined during the kickoff and discovery phase.`.trim();
}

export function downloadFile(content: string, filename: string, type: string): void {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
